### ISSUE TITLE
Bug: app needs browserlist key in package.json in order to build

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe.engineering#18]
Error on build. As of `create-react-app` `v2.0` the app needs `browserlis` key in `package.json` in order to build

```
As of react-scripts >=2 you must specify targeted browsers.
Please add a browserslist key to your package.json.
```

**Comment by guylepage3** [comment]
Just needed to say `y` to browserlist to be added when running app for the first time...

See.. https://reactjs.org/blog/2018/10/01/create-react-app-v2.html

 ```
When you run npm start for the first time after the upgrade, you’ll get a prompt asking about which browsers you’d like to support. Press y to accept the default ones. They’ll be written to your package.json and you can edit them any time. Create React App will use this information to produce smaller CSS bundles if you only target modern browsers.
```

**Comment by mcfriend99** [comment]
Any help here?? It's just exiting after typing `Y` and pressing enter. Browserlist is causing the app not to start

**Comment by brandonturpin** [comment]
Same for me, I push Y and then get this error. Also BrowserList is in there so not sure why I even get the error.

**Comment by ercandemir** [comment]
Run on cmd `npm install browserslist`
