### ISSUE TITLE
Evaluate whether Typeform suits better than Google Forms

### ISSUE THREAD

**Issue by vsund** [universelabs/universe.engineering#19]
The [questionnaire](https://docs.google.com/forms/d/e/1FAIpQLSc_bgvZ3EKlJN8LlwnGQPOK-WyaIg3T7YepnRXftI6d1LLWlA/viewform) currently uses Google Forms.

[Typeform](https://www.typeform.com) provides a way better user experience for answering forms. Though their free plan is limited to 100 responses and 10 questions (and their first plan is already 25€/month).

Might be cool enough though :)

**Comment by guylepage3** [comment]
Closing.
