### ISSUE TITLE
UX Review

### ISSUE THREAD

**Issue by pftchal** [universelabs/universe.engineering#55]

**Comment by pftchal** [comment]
Overview: 

Universe.engineering is Open source, blockchain agnostic key management. With Universe, users sign up once and gain access to leading blockchains. Universe’s key manager gives you quick access to passphrases, private keys, and seeds, all in one place.

**Comment by pftchal** [comment]
I will start doing UX reviews from this week for the website and most importantly the products of Universe. Since the products are not on the website yet, I will start from the UX of the website. I will share some personal opinions, also I will try to do some researches on similar blockchain/crypto websites or products, to do some comparison. I will update my reviews hopefully every week, whenever I find anything that can possibly be improved. Please leave your comments below if you find anything interesting or you have a different opinion and advice.
 
**UX Review - 05/15/2019**

**Website reviews:

1. The order of introduction in the hero section**

The short description below the 'subscribe' button is not in a reasonable order, as it clearly describes what the website does in one sentence, comparing to the long description above. Users won't invest much time to understand what a website does at first glance. Therefore, for a better visual hierarchy, the short description could be below the headline in the hero section. And the longer description could be either below the short description. In future web development, it should be in the About section to further explain what the website does.

<img width="1278" alt="Screen Shot 2019-05-15 at 9 16 31 PM" src="https://user-images.githubusercontent.com/48525282/57819872-49c53880-7758-11e9-9ee8-53390283ef87.png">

Something like this looks simple and easy to read, grasp attention right away.

<img width="1240" alt="Screen Shot 2019-05-15 at 9 53 15 PM" src="https://user-images.githubusercontent.com/48525282/57820763-0bca1380-775c-11e9-9ea7-e348b136a0b8.png">

**2. Subscribe element in the Footer section does not align well.**

The subscribe element in the footer section does drag users' eyes immediately in the footer, but it also seems to be off while not really aligning well with other elements. It can either be moved upward to be aligned with the Universe logo, or can be adjusted to a smaller size.
<img width="1280" alt="Screen Shot 2019-05-15 at 9 18 22 PM" src="https://user-images.githubusercontent.com/48525282/57820048-1800a180-7759-11e9-9524-4a7572d53566.png">

**3. Lack of links on the homepage.**
I know this whole website is still under development, but since the signup page is there, there could be a 'Sign up' and 'Sign in' option on the navigation bar in the future.

**4. Development for Sign-in and email notification**
It will be less confusing to add Sign-in under the Get Started button in the Sign-up page when the backend is developed. And it is important to send an email notification to users when they successfully sign up for an account. It is confusing for the users if they cannot be directed to the sign-in page from the Sign-up page. 

<img width="1234" alt="Screen Shot 2019-05-15 at 9 20 04 PM" src="https://user-images.githubusercontent.com/48525282/57820289-2dc29680-775a-11e9-9f7c-73f3346cc011.png">

**5. No product information on Dashboard.**
Under the headline 'Your Keys', it will be more clear to have further instructions, on how to use the keys or things to keep in mind about etc. Also the tabs here can not be expanded, so basically there is no product information nor the keys were generated. It will also be more thoughtful to add a description to each key and its different purposes.

<img width="1280" alt="Screen Shot 2019-05-14 at 5 11 40 PM" src="https://user-images.githubusercontent.com/48525282/57820411-ade8fc00-775a-11e9-94cf-ccd68b98e968.png">

6. Short words for the web title 
So the title of the website is only Universe, so it will be confusing to the user if they are trying to figure out what the website does. 

<img width="129" alt="Screen Shot 2019-05-15 at 9 48 38 PM" src="https://user-images.githubusercontent.com/48525282/57820590-70d13980-775b-11e9-94ee-d58b2c01e595.png">

It will be nice to have something like this:

<img width="254" alt="Screen Shot 2019-05-15 at 9 51 36 PM" src="https://user-images.githubusercontent.com/48525282/57820657-ac6c0380-775b-11e9-91c0-fe8f97b408fa.png">

**Comment by guylepage3** [comment]
Very nice review @pftchal!! Well done! 👍 I will dive deeper into this tonight, provide feedback and then create new issues based upon all this. Really thorough job. This is exactly what we were looking for. Thank you. 😄
