### ISSUE TITLE
Hero text wording

### ISSUE THREAD

**Issue by faddat** [universelabs/universe.engineering#68]
**Hero Text**
Our new hero text uses the world decentralized too much, we should use that word just once.  

<img width="596" alt="Screen Shot 2019-09-08 at 4 16 53 PM" src="https://user-images.githubusercontent.com/7142025/64493961-e1ddb500-d254-11e9-9754-b57c2c578968.png">

# Suggested Text
Login Made Easy.  Universe is a decentralized login and private key recovery protocol.  Sign up for Web 3.0 just once.  Never deal with key management again.

**Comment by guylepage3** [comment]
Updated over the weekend. Closing.
